const icons = {
  sun: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5"></circle><path d="M12 2v3M12 19v3M4.93 4.93l2.12 2.12M16.95 16.95l2.12 2.12M2 12h3M19 12h3M4.93 19.07l2.12-2.12M16.95 7.05l2.12-2.12"></path></svg>',
  cap: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 9 9-4 9 4-9 4-9-4Z"></path><path d="M7 11.2v4.1c2.8 2 7.2 2 10 0v-4.1M21 9v5"></path></svg>',
  book: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21.5v-16Z"></path><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5a2.5 2.5 0 0 1 2.5 2.5v-16Z"></path></svg>',
  plane: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m3 13 7-2 4-7 2 .5-1 7 5 1.5c1 .3 1.5 1.8.6 2.4l-.6.4-5-1-3 5-1.5-.5.5-5-7-1.5L3 13Z"></path></svg>',
  clipboard: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="4" width="14" height="17" rx="1.5"></rect><path d="M9 4.5V3h6v1.5M8 12l2.2 2.2L16 8.5"></path></svg>'
};
const categoryCopy = { summer: 'Find funded learning, internships, and enrichment for your summer.', scholarships: 'Find funding for school, training, and the next chapter.', courseware: 'Build skills and confidence with accessible online learning.', flyins: 'Get a closer look at colleges through funded campus visits.', testing: 'Find test prep and fee support to keep your options open.' };
let resources = [];
const footerText = 'A steady starting point for students and the counselors who support them.';

function escapeHtml(value = '') { return value.replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character])); }
function resourceCard(item) {
  const tags = item.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join('');
  return `<article class="resource-card reveal"><div class="card-top"><span class="category-label">${escapeHtml(item.label)}</span><span class="card-arrow" aria-hidden="true">&#8599;</span></div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary)}</p><dl class="resource-meta"><div><dt>Deadline / dates</dt><dd>${escapeHtml(item.deadline) || 'See site'}</dd></div>${item.cost ? `<div><dt>Cost / award</dt><dd>${escapeHtml(item.cost)}</dd></div>` : ''}</dl><div class="tag-list">${tags}</div><a class="text-link" href="${escapeHtml(item.url)}" target="_blank" rel="noopener">Visit opportunity <span aria-hidden="true">&#8594;</span></a></article>`;
}
function setupNavigation() { const toggle = document.querySelector('.menu-toggle'); const nav = document.querySelector('.site-nav'); if (!toggle) return; toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); nav.classList.toggle('is-open', !open); }); }
function setupSearch() { document.querySelectorAll('.search-form').forEach(form => form.addEventListener('submit', event => { event.preventDefault(); const query = new FormData(form).get('q').trim(); if (query) window.location.href = `index.html?q=${encodeURIComponent(query)}#search-results`; })); const query = new URLSearchParams(window.location.search).get('q'); if (query && document.querySelector('#search-results')) { document.querySelector('#hero-search').value = query; renderSearch(query); } }
function renderSearch(query) {
  const target = document.querySelector('#search-results');
  const words = query.toLowerCase().split(/\s+/).filter(word => !['near', 'in', 'for', 'the', 'and', 'a'].includes(word));
  const locationTerms = query.match(/(?:near|in)\s+([a-z][a-z\s]+)/i);
  const hits = resources.map(item => {
    const searchable = `${item.title} ${item.summary} ${item.label} ${item.tags.join(' ')}`.toLowerCase();
    const score = words.reduce((total, word) => total + (searchable.includes(word) ? 1 : 0), 0);
    return { item, score };
  }).filter(hit => hit.score).sort((a, b) => b.score - a.score).slice(0, 12);
  target.innerHTML = `<div class="section-heading"><div><p class="eyebrow">Search results</p><h2>${hits.length} result${hits.length === 1 ? '' : 's'} for “${escapeHtml(query)}”</h2></div>${locationTerms ? '<p class="location-note">We do not have location data in this collection, so these results are matched by keywords rather than distance.</p>' : ''}</div><div class="search-results">${hits.length ? hits.map(({ item }) => `<a class="search-result" href="${item.pageUrl}"><span class="category-label">${escapeHtml(item.label)}</span><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.summary)}</span><b aria-hidden="true">&#8599;</b></a>`).join('') : `<div class="empty-state no-results"><span class="empty-mark" aria-hidden="true">?</span><h3>We couldn't find anything related to your search.</h3><p>Try a different search term, or browse the category pages directly.</p><div class="empty-links"><a class="text-link" href="summer-programs.html">Summer programs</a><a class="text-link" href="scholarships.html">Scholarships</a><a class="text-link" href="courseware.html">Courseware</a><a class="text-link" href="fly-in-programs.html">Fly-in programs</a><a class="text-link" href="testing.html">Testing &amp; waivers</a></div></div>`}</div>`;
}
function setupHome() { const grid = document.querySelector('#category-grid'); if (grid) { grid.innerHTML = Object.entries(DATASETS).map(([key, dataset], index) => `<a class="category-card reveal accent-${index + 1}" href="${dataset.url}"><span class="category-icon">${icons[dataset.icon]}</span><span><strong>${dataset.label}</strong><small>${categoryCopy[key]}</small></span><b aria-hidden="true">&#8594;</b></a>`).join(''); } if (!document.querySelector('#search-results')) { const section = document.createElement('section'); section.id = 'search-results'; section.className = 'search-section'; document.querySelector('main').append(section); } }
function setupCategory() { const page = document.querySelector('.category-page'); if (!page) return; const key = page.dataset.category; if (key === 'scholarships') document.querySelector('.category-hero .lede').textContent = 'Find scholarships and awards that help cover the cost of college and training.'; if (key === 'testing') document.querySelector('.category-hero .lede').textContent = 'Find fee waivers, prep resources, and affordable ways to take college entrance exams.'; let filtered = resources.filter(item => item.key === key); const grid = document.querySelector('#resource-grid'), count = document.querySelector('.result-count'), filter = document.querySelector('#tag-filter'), sort = document.querySelector('#sort-button'); [...new Set(filtered.flatMap(item => item.tags))].sort().forEach(tag => filter.insertAdjacentHTML('beforeend', `<option value="${escapeHtml(tag)}">${escapeHtml(tag)}</option>`)); const render = () => { const selected = filter.value; const visible = filtered.filter(item => selected === 'all' || item.tags.includes(selected)); count.textContent = visible.length; grid.innerHTML = visible.length ? visible.map(resourceCard).join('') : '<p class="empty-state">No resources match that eligibility tag.</p>'; observeReveals(); }; filter.addEventListener('change', render); sort.addEventListener('click', () => { const ascending = sort.getAttribute('aria-pressed') !== 'true'; sort.setAttribute('aria-pressed', String(ascending)); filtered = [...filtered].sort((a, b) => ascending ? a.deadline.localeCompare(b.deadline) : b.deadline.localeCompare(a.deadline)); render(); }); render(); }
function observeReveals() { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: 0.08 }); document.querySelectorAll('.reveal:not(.is-visible)').forEach(element => observer.observe(element)); }
document.addEventListener('DOMContentLoaded', async () => { document.querySelector('#year').textContent = new Date().getFullYear(); document.querySelectorAll('.site-footer p:first-of-type').forEach(element => { element.textContent = footerText; }); setupNavigation(); setupHome(); setupSearch(); try { resources = await loadResources(); setupCategory(); const query = new URLSearchParams(window.location.search).get('q'); if (query) renderSearch(query); } catch (error) { document.querySelectorAll('[aria-live="polite"]').forEach(target => { target.innerHTML = '<p class="empty-state">Resources could not be loaded. Please try again from a local web server.</p>'; }); } observeReveals(); });